# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /Users/thangle/volumes/mysql_data:/var/lib/mysql
      - /Users/thangle/volumes/mysql/my.cnf:/etc/mysq/my.cnf
  redis:
    image: "redis:alpine"
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
    - /Users/thangle/volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf
    - /Users/thangle/volumes/redis/data:/data
    sysctls:
      - net.core.somaxconn=511
    ports:
      - "6379:6379"
    # networks:
    #   node_net:
    #     ipv4_address: 172.28.1.3
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080